
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/ohiomannnn/HBMsNTM-NEO-EDITION/issues"

[[mods]]
modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

# haha, kill yourself
#updateJSONURL="https://change.me.example.invalid/updates.json"

displayURL="https://github.com/ohiomannnn/HBMsNTM-NEO-EDITION"

logoFile= "logo.png"

#credits=""

authors="${mod_authors}"

description='''${mod_description}'''

[[mixins]]
config="hbmsntm.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
